# Generated by Django 4.1 on 2022-10-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_answer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
