# Generated by Django 4.1 on 2022-10-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_answer_username_question_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
