# Generated by Django 4.1 on 2022-10-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
