# Generated by Django 4.1 on 2022-10-30 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0011_alter_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
    ]
