# Generated by Django 4.1 on 2022-10-31 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0014_alter_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='imageURL',
        ),
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
    ]
