# Generated by Django 4.1 on 2022-10-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0015_remove_event_imageurl_remove_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imageURL',
            field=models.TextField(null=True),
        ),
    ]
