# Generated by Django 4.1 on 2022-10-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0017_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
