# Generated by Django 4.1 on 2022-10-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0018_event_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='status',
            new_name='category',
        ),
    ]
