# Generated by Django 4.1 on 2022-10-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0020_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='month',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
