# Generated by Django 4.1 on 2022-12-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0024_alter_event_date_alter_event_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='imageURL',
        ),
    ]
