# Generated by Django 4.1 on 2022-10-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekwisata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objekwisata',
            name='lokasi',
            field=models.CharField(default='Indonesia', max_length=250),
        ),
    ]
