# Generated by Django 4.1 on 2022-10-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekwisata', '0002_objekwisata_lokasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objekwisata',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='objekwisata',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='objekwisata',
            name='lokasi',
        ),
        migrations.AddField(
            model_name='objekwisata',
            name='address_link',
            field=models.URLField(default='https://goo.gl/maps/5D8wXfWReu4EhZNB6'),
        ),
        migrations.AddField(
            model_name='objekwisata',
            name='description',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='objekwisata',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
