# Generated by Django 4.1 on 2022-10-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekwisata', '0004_objekwisata_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objekwisata',
            name='address_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='objekwisata',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='objekwisata',
            name='location',
            field=models.CharField(max_length=20),
        ),
    ]
