# Generated by Django 4.1 on 2022-10-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekwisata', '0005_alter_objekwisata_address_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objekwisata',
            name='imageURL',
            field=models.TextField(null=True),
        ),
    ]
