# Generated by Django 4.1 on 2022-10-31 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objekwisata', '0006_objekwisata_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objekwisata',
            old_name='image',
            new_name='imageAttraction',
        ),
    ]
