# Generated by Django 4.1 on 2022-12-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objekwisata', '0009_objekwisata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objekwisata',
            name='image',
        ),
        migrations.RemoveField(
            model_name='objekwisata',
            name='imageURL',
        ),
    ]
