# Generated by Django 4.1 on 2022-12-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekwisata', '0010_remove_objekwisata_image_remove_objekwisata_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objekwisata',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objekwisata',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objekwisata',
            name='title',
            field=models.TextField(),
        ),
    ]
