# Generated by Django 4.1 on 2022-10-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umkm',
            name='link_image',
        ),
        migrations.AddField(
            model_name='umkm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
