# Generated by Django 4.1 on 2022-10-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkm', '0002_remove_umkm_link_image_umkm_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umkm',
            name='link_website',
            field=models.URLField(),
        ),
    ]
