# Generated by Django 4.1 on 2022-10-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkm', '0003_alter_umkm_link_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='umkm',
            name='imageURL',
            field=models.TextField(null=True),
        ),
    ]
