# Generated by Django 4.1 on 2022-11-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umkm', '0007_alter_umkm_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umkm',
            name='user',
        ),
    ]
