# Generated by Django 4.1 on 2022-10-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
