# Generated by Django 4.1 on 2022-10-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_trips_notes_alter_trips_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='trip_date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
