# Generated by Django 4.1 on 2022-10-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_trips_trip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
