# Generated by Django 4.1 on 2022-10-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_trips_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
