# Generated by Django 4.1 on 2022-11-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_trips_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='trip_date',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
