# Generated by Django 4.1 on 2022-11-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_trips_trip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='trip_date',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
